project:
  type: website
  output-dir: docs


website:
  title: "Malo Jan"
  description: "Website of Malo Jan"
  site-url: "1"
  repo-url: '2'
  open-graph: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: data.qmd
        text: Data
      - href: teaching.qmd
        text: Teaching
      - href: CV_Malo_Jan.pdf
        text: CV

page-footer:
    background: dark # or dark
    left:
      - "Copyright 2024, Malo Jan"
    right:
      - icon: github
        href: https://github.com/malojan
      - icon: twitter
        href: https://twitter.com/malo_jn

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    highlight-style: tango
    page-layout: full



