project:
  type: website
  output-dir: docs


website:
  title: "Malo Jan"
  description: "Website of Malo Jan"
  site-url: "1"
  repo-url: '2'
  open-graph: true
  twitter-card: 
    creator: "@malojn"
    site: "@linogaliana"
    card-style: "summary_large_image"
  navbar:
    background: "darkgreen"
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: teaching.qmd


format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    highlight-style: tango
    page-layout: full



